### ISSUE TITLE
docker : candid attempt

### ISSUE THREAD

**Issue by loicjaouen** [loicjaouen/arches_issues#1]
trying it out of the box

**Comment by loicjaouen** [comment]
setting up: forked [offcial arches](https://github.com/archesproject/arches) into [this repo](https://github.com/loicjaouen/arches)

syncing code to version: 7.3.0

```bash
git checkout -b 7.3.0_composed 7.3.0
```

Simply try it:
```bash
docker compose up
```

**Comment by loicjaouen** [comment]
- [ ] met problem #2

**Comment by loicjaouen** [comment]
then:
- [ ] pip wheel args #3

**Comment by loicjaouen** [comment]
- [ ] node version is too old for the listed dependencies #4

**Comment by loicjaouen** [comment]
- [ ] missing python dependencies #5

**Comment by loicjaouen** [comment]
- [ ] elasticsearch client/server version mismatch? #6

**Comment by loicjaouen** [comment]
Docker build:
> [+] Building 3982.1s (33/33) FINISHED                                                                                                                                                                              

https://xkcd.com/303/

**Comment by loicjaouen** [comment]
- [ ] webpack statics are missing #7
